/*
 * TIMER1_configuration.h
 *
 *  Created on: Apr 26, 2024
 *      Author: DELL
 */

#ifndef INCLUDE_MCAL_TIMER1_TIMER1_CONFIGURATION_H_
#define INCLUDE_MCAL_TIMER1_TIMER1_CONFIGURATION_H_



#endif /* INCLUDE_MCAL_TIMER1_TIMER1_CONFIGURATION_H_ */
