/*
 * DIO_configuration.h
 *
 *  Created on: Feb 24, 2024
 *      Author: DELL
 */

#ifndef INCLUDE_MCAL_DIO_DIO_CONFIGURATION_H_
#define INCLUDE_MCAL_DIO_DIO_CONFIGURATION_H_

/*OPtions Are:- DIO_INPUT - DIO_OUTPUT*/
#define PORTA_PIN0_DIRECTION DIO_INPUT
#define PORTA_PIN1_DIRECTION DIO_INPUT
#define PORTA_PIN2_DIRECTION DIO_INPUT
#define PORTA_PIN3_DIRECTION DIO_INPUT
#define PORTA_PIN4_DIRECTION DIO_INPUT
#define PORTA_PIN5_DIRECTION DIO_INPUT
#define PORTA_PIN6_DIRECTION DIO_OUTPUT
#define PORTA_PIN7_DIRECTION DIO_OUTPUT

#define PORTB_PIN0_DIRECTION DIO_OUTPUT
#define PORTB_PIN1_DIRECTION DIO_OUTPUT
#define PORTB_PIN2_DIRECTION DIO_OUTPUT
#define PORTB_PIN3_DIRECTION DIO_OUTPUT
#define PORTB_PIN4_DIRECTION DIO_OUTPUT
#define PORTB_PIN5_DIRECTION DIO_OUTPUT
#define PORTB_PIN6_DIRECTION DIO_OUTPUT
#define PORTB_PIN7_DIRECTION DIO_OUTPUT

#define PORTC_PIN0_DIRECTION DIO_OUTPUT
#define PORTC_PIN1_DIRECTION DIO_OUTPUT
#define PORTC_PIN2_DIRECTION DIO_OUTPUT
#define PORTC_PIN3_DIRECTION DIO_OUTPUT
#define PORTC_PIN4_DIRECTION DIO_OUTPUT
#define PORTC_PIN5_DIRECTION DIO_OUTPUT
#define PORTC_PIN6_DIRECTION DIO_OUTPUT
#define PORTC_PIN7_DIRECTION DIO_OUTPUT

#define PORTD_PIN0_DIRECTION DIO_OUTPUT
#define PORTD_PIN1_DIRECTION DIO_OUTPUT
#define PORTD_PIN2_DIRECTION DIO_OUTPUT
#define PORTD_PIN3_DIRECTION DIO_OUTPUT
#define PORTD_PIN4_DIRECTION DIO_OUTPUT
#define PORTD_PIN5_DIRECTION DIO_OUTPUT
#define PORTD_PIN6_DIRECTION DIO_OUTPUT
#define PORTD_PIN7_DIRECTION DIO_OUTPUT

/*DIRECTION OUTPUT:- DIO_HIGH - DIO_LOW*/
/*DIRECTION INPUT:-  DIO_PULLUP - DIO_FLOATING */
#define PORTA_PIN0_VALUE DIO_PULLUP
#define PORTA_PIN1_VALUE DIO_PULLUP
#define PORTA_PIN2_VALUE DIO_PULLUP
#define PORTA_PIN3_VALUE DIO_PULLUP
#define PORTA_PIN4_VALUE DIO_PULLUP
#define PORTA_PIN5_VALUE DIO_PULLUP
#define PORTA_PIN6_VALUE DIO_HIGH
#define PORTA_PIN7_VALUE DIO_HIGH

#define PORTB_PIN0_VALUE DIO_LOW
#define PORTB_PIN1_VALUE DIO_LOW
#define PORTB_PIN2_VALUE DIO_LOW
#define PORTB_PIN3_VALUE DIO_LOW
#define PORTB_PIN4_VALUE DIO_LOW
#define PORTB_PIN5_VALUE DIO_LOW
#define PORTB_PIN6_VALUE DIO_LOW
#define PORTB_PIN7_VALUE DIO_LOW

#define PORTC_PIN0_VALUE DIO_LOW
#define PORTC_PIN1_VALUE DIO_LOW
#define PORTC_PIN2_VALUE DIO_LOW
#define PORTC_PIN3_VALUE DIO_LOW
#define PORTC_PIN4_VALUE DIO_LOW
#define PORTC_PIN5_VALUE DIO_LOW
#define PORTC_PIN6_VALUE DIO_LOW
#define PORTC_PIN7_VALUE DIO_LOW

#define PORTD_PIN0_VALUE DIO_HIGH
#define PORTD_PIN1_VALUE DIO_HIGH
#define PORTD_PIN2_VALUE DIO_HIGH
#define PORTD_PIN3_VALUE DIO_HIGH
#define PORTD_PIN4_VALUE DIO_HIGH
#define PORTD_PIN5_VALUE DIO_HIGH
#define PORTD_PIN6_VALUE DIO_HIGH
#define PORTD_PIN7_VALUE DIO_HIGH

#endif /* INCLUDE_MCAL_DIO_DIO_CONFIGURATION_H_ */
